name: python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v1
    - name: set up python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r python/requirements.txt

    - name: lint with flake8
      run: |
        flake8 test_jims_challenge.py
        flake8 python/jims_challenge.py

    - name: test with pytest
      run: pytest -s test_jims_challenge.py

